### ISSUE TITLE
Add react/jsx-no-target-blank to config/react.js

### ISSUE THREAD

**Issue by tosmolka** [microsoft/eslint-plugin-sdl#23]
**Is your feature request related to a problem? Please describe.**
When scanning React apps, I would like to be warned about external links or forms without noreferrer or noopener in their rel attribute. This is quite common security requirement (see https://web.dev/external-anchors-use-rel-noopener/ and other public sources). 

**Describe the solution you'd like**
I think [react/jsx-no-target-blank](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md) does a good job of detecting most common scenarios, I would suggest adding it to SDL Required ruleset for React apps ([./config/react.js](https://github.com/microsoft/eslint-plugin-sdl/blob/main/config/react.js)). 

I would also consider rule config that is slightly more strict that the defaults, such as:
```js
{
  allowReferrer: false,
  enforceDynamicLinks: 'always',
  warnOnSpreadAttributes: true,
  links: true,
  forms: true
}
```

**Describe alternatives you've considered**
I don't think it makes sense to implement and maintain custom rule in this case. 

**Additional context**
This check was implemented in tslint via [react-anchor-blank-noopener](https://github.com/microsoft/tslint-microsoft-contrib/blob/0b389f96d036a27b49cb6a0a262f07c9f813c15e/src/reactAnchorBlankNoopenerRule.ts) but for some reason was omitted during migration of SDL rules to eslint.

**Comment by A-Katopodis** [comment]
Hi Tobias,

Thanks for the pointer we have a PR underway to update it:
#26

**Comment by tosmolka** [comment]
Thank you @A-Katopodis
