### ISSUE TITLE
Migrate from @microsoft/sdl/react-iframe-missing-sandbox to react/iframe-missing-sandbox

### ISSUE THREAD

**Issue by tosmolka** [microsoft/eslint-plugin-sdl#30]
**Is your feature request related to a problem? Please describe.**
[eslint-plugin-react@7.29.0](https://github.com/yannickcr/eslint-plugin-react/releases/tag/v7.29.0) now includes rule [react/iframe-missing-sandbox](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/iframe-missing-sandbox.js) which is slightly improved version of [@microsoft/sdl/react-iframe-missing-sandbox](https://github.com/microsoft/eslint-plugin-sdl/blob/main/lib/rules/react-iframe-missing-sandbox.js).

Unless there is a good reason to keep maintaining two versions of essentially identical rule I would suggest to deprecate @microsoft/sdl/react-iframe-missing-sandbox in favor of react/iframe-missing-sandbox. 

**Describe the solution you'd like**
- Update config/react.js and switch from @microsoft/sdl/react-iframe-missing-sandbox to react/iframe-missing-sandbox
- Update version of eslint-plugin-react in package.json
- This is potentially breaking change, consider increasing minor package version, releasing in multiple stages, publishing release notes, etc. 

**Describe alternatives you've considered**
Backport changes from react/iframe-missing-sandbox to @microsoft/sdl/react-iframe-missing-sandbox and continue maintaining two versions

**Comment by mkacmar** [comment]
Done, closing.
