### ISSUE TITLE
[no-insecure-url] Autofix that replaces HTTP with HTTPS in literals and templateliterals

### ISSUE THREAD

**Issue by mozfreddyb** [microsoft/eslint-plugin-sdl#37]
**Is your feature request related to a problem? Please describe.**
We at Mozilla would like to make more use of the `no-insecure-url` rule of this plugin.. For this to work best, we'd prefer if the rule had the `--fix` functionality.

**Describe the solution you'd like**
We actually have a prototype patch that works for Literals and would be easy to adapt to TemplateLiterals and (obviously) takes the exceptions and blocklists into account.

**Describe alternatives you've considered**
N/A

**Additional context**
Not sure, but feel free to ask. We'd really like to make this work.

**Comment by tosmolka** [comment]
@A-Katopodis , @Vflouirac , kind reminder, do you have any update regarding the issue? Thank you.

**Comment by Vflouirac** [comment]
Hi Tobias,

Thanks for the ping. We should be able to take care of it next iteration :)

Regards,
Vivien
________________________________

**Comment by mozfreddyb** [comment]
Hi,
We at Mozilla already have started implementing a prototype for your review in #39. 
We'd be happy to see this move forward.
