### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by mozfreddyb** [microsoft/eslint-plugin-sdl#47]
**Is your feature request related to a problem? Please describe.**
Firefox is currently on a fork of this package. 

**Describe the solution you'd like**
With #39 merged, it would be great for us if this package would create a new release

**Describe alternatives you've considered**
Of course, we could always stay on our fork.... 🙄

**Comment by freddyb** [comment]
@Vflouirac Can you help us out here?

**Comment by Vflouirac** [comment]
Hello @freddyb,

Sorry for the delay in release, we had some other items on our plate, we will try to make a release early next week

**Comment by Standard8** [comment]
Hi @Vflouirac, sorry for nagging, is there any chance of this happening soon?

**Comment by Vflouirac** [comment]
Hello @freddyb  @Standard8 

My apologies for the delay. You should find the new release with the missing content. 

Please let me know if you encounter any issues

**Comment by Standard8** [comment]
Thank you, it looks good.

I think we can close this now.
