### ISSUE TITLE
use of recommended config requires tsconfig coverage of all files

### ISSUE THREAD

**Issue by jason-ha** [microsoft/eslint-plugin-sdl#5]
When `plugin:@microsoft/sdl/recommended` is added to eslint configuration errors are generated for all files not listed in tsconfig.json file - not just typescript files.

Example error:
```
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\foo\gulpfile.js.
The file must be included in at least one of the projects provided
```

**Expected behavior**
@typescript-eslint/parser is only applied to **/*.{ts,tsx} files as listed in the overrides and thus no Parsing errors.

**Comment by A-Katopodis** [comment]
Completed as part #6
