### ISSUE TITLE
Consider migrating from `eslint-plugin-node` to `eslint-plugin-n`

### ISSUE THREAD

**Issue by tido64** [microsoft/eslint-plugin-sdl#52]
**Describe the bug**

Consider migrating from `eslint-plugin-node` to [`eslint-plugin-n`](https://github.com/eslint-community/eslint-plugin-n) as the former is no longer maintained: https://github.com/mysticatea/eslint-plugin-node/issues/300

**To Reproduce**

n/a

**Expected behavior**

n/a

**Screenshots**

n/a

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser: any
 - Version: any

**Additional context**

For additional context, see https://github.com/mysticatea/eslint-plugin-node/issues/300

**Comment by mkacmar** [comment]
Migrated in https://github.com/microsoft/eslint-plugin-sdl/pull/60 (older plugin didn't have ESLint v9 compatibility)
