### ISSUE TITLE
Prepare custom rules for ESLint v9

### ISSUE THREAD

**Issue by tido64** [microsoft/eslint-plugin-sdl#53]
**Describe the bug**

The upcoming major release of ESLint includes several breaking changes for rule authors: https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/

**To Reproduce**

n/a

**Expected behavior**

n/a

**Screenshots**

n/a

**Desktop (please complete the following information):**

 - OS: any
 - Browser: any
 - Version: any

**Smartphone (please complete the following information):**

 - Device: any
 - OS: any
 - Browser: any
 - Version: any

**Additional context**

Intro to ESLint's new config format: https://eslint.org/blog/2022/08/new-config-system-part-2/

**Comment by mkacmar** [comment]
Merged in https://github.com/microsoft/eslint-plugin-sdl/pull/60
