### ISSUE TITLE
http://localhost should be allowed by @microsoft/sdl/no-insecure-url

### ISSUE THREAD

**Issue by jason-ha** [microsoft/eslint-plugin-sdl#7]
`http://localhost` is common for some testing scenarios and situations where communication does not leave the OS are not a risk.

**To Reproduce**
1. Add `'http://localhost'` use in code.
2. Enable recommended configuration.
3. Run eslint
4. See report similar to:

```
Error @microsoft/sdl/no-insecure-url: Insecure protocols such as [HTTP](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol) or [FTP](https://en.wikipedia.org/wiki/File_Transfer_Protocol) should be replaced by their encrypted counterparts ([HTTPS](https://en.wikipedia.org/wiki/HTTPS), [FTPS](https://en.wikipedia.org/wiki/FTPS)) to avoid sending (potentially sensitive) data over untrusted network in plaintext.: Do not use insecure URLs
```

**Related**
See [tslint no-http issue](https://github.com/microsoft/tslint-microsoft-contrib/pull/423) where localhost was resolved to be allowed.

**Expected behavior**
`http://localhost` should be allowed.

**Comment by A-Katopodis** [comment]
Issue was resolved with PRs:
#11 
#12
