### ISSUE TITLE
Mark 1.0.0 as latest on npm

### ISSUE THREAD

**Issue by vchernin** [microsoft/eslint-plugin-sdl#75]
Please mark `1.0.0` as the `latest` version on npm. `0.2.2` is the current latest npm release.
https://www.npmjs.com/package/@microsoft/eslint-plugin-sdl?activeTab=versions. npm installs the latest version by default if no version is specified.

`1.0.0` is the latest release according to GitHub releases https://github.com/microsoft/eslint-plugin-sdl/releases/tag/v1.0.0. Perhaps the `1.0.0` release is not yet ready for production, but in that case it should probably not be marked as the latest release on GitHub.

**Comment by mkacmar** [comment]
Yeah, thanks for a reminder. I'll tag 1.0.0 as latest on npm next week.

**Comment by mkacmar** [comment]
This has been done now, closing. Let us know if you encounter any issues with 1.0.0 @vchernin.
